autoencoder:
  _target_: pytorch_lightning.Trainer
  min_epochs: 1
  max_epochs: 10
  accelerator: gpu
  devices: 1

product_encode:
  _target_: pytorch_lightning.Trainer
  min_epochs: 1
  max_epochs: 10
  accelerator: gpu
  devices: 1