node {
     stage('Clone repository') {
         checkout scm
     }

     stage('Build Bento') {
        sh 'bentoml build -f bentofile/sweep_best/bentofile_human_size.yaml'
     }

     stage ('Containerize') {
        sh 'bentoml containerize human_size_predict:latest -t 210651441624.dkr.ecr.ap-northeast-2.amazonaws.com/human_size_predict:latest'
     }

     stage('Push image') {
         sh 'rm  ~/.dockercfg || true'
         sh 'rm ~/.docker/config.json || true'
         
         docker.withRegistry('https://210651441624.dkr.ecr.ap-northeast-2.amazonaws.com', 'ecr:ap-northeast-2:aws-ecr-full-access') {
             app.push("${env.BUILD_NUMBER}")
             app.push("latest")
     }
  }
}