segment:
  _target_: torchvision.transforms.Compose
  transforms: 
    - _target_: torchvision.transforms.ToTensor
    - _target_: torchvision.transforms.Resize
      size: [1280, 1280]

autoencoder:
  _target_: torchvision.transforms.Compose
  transforms: 
    - _target_: torchvision.transforms.ToTensor
    - _target_: src.data.preprocess.Crop
      threshold: 0.5
    - _target_: torchvision.transforms.Resize
      size: [512, 512]

product_encode:
  _target_: torchvision.transforms.Compose
  transforms: 
    - _target_: torchvision.transforms.ToTensor
    - _target_: torchvision.transforms.Resize
      size: [128, 128]