segment:
  _target_: torch.nn.DataParallel
  module: 
    _target_: src.SemanticGuidedHumanMatting.model.model.HumanMatting

autoencoder:
  _target_: src.models.lightning_modules.CombAutoEncoderModule
  learning_rate: 1e-4
  input_shape: ${preprocess.autoencoder.transforms.2.size}
  nblocks: 5
  filters: 32
  latent_dim: 256

regression:
  _target_: sklearn.kernel_ridge.KernelRidge
  alpha: 0.2
  kernel: poly
  degree: 3

product_encode:
  _target_: src.models.lightning_modules.ProductModule
  learning_rate: 1e-4
  bbox_loss_weight: 1.0
  embedding_dim: 64