human_size:
  _target_: pytorch_lightning.loggers.WandbLogger
  project: human_size_predict
  save_dir: "${paths.output_dir}"
  offline: False

product_encode:
  _target_: pytorch_lightning.loggers.WandbLogger
  project: item_based_recommendation
  save_dir: "${paths.output_dir}"
  offline: False