pipeline {
    agent any

    stages {
        stage('Bentoml to docker image'){
            steps {
                sh 'cd /home/shin/anaconda3/envs'
                sh 'ls -al'
                sh 'source /home/shin/anaconda3/bin/activate /home/shin/anaconda3/envs/fashion-ubf-env'
                sh 'bentoml serve serving.bentoml.service_fashion_ubf:svc --development --reload'
            }
        }
    }  
}