defaults:
  - model: v1.yaml
  - data: v1.yaml
  - trainer: v1.yaml
  - logger: wandb.yaml
  - paths: default.yaml
  - preprocess: v1.yaml
  - hydra: default.yaml
optimizer.config.learning_rate:
train: product_encode